[package]
name = "cyme"
authors = ["John Whittington <john@jbrengineering.co.uk>"]
description = "List system USB buses and devices; a modern `lsusb` that attempts to maintain compatibility with, but also add new features"
repository = "https://github.com/tuna-f1sh/cyme"
readme = "README.md"
license = "GPL-3.0-or-later"
version = "0.7.3"
edition = "2021"
keywords = ["usb", "lsusb", "system_profiler", "macos", "libusb"]
categories = ["command-line-utilities"]
exclude = ["./img/**", ".github"]

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }
colored = "2.0.0"
itertools = "0.10.5"
lazy_static = "1.4.0"
rusb = { version = "0.9.1", optional = true }
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
serde_with = "2.0.1"
simple_logger = "4.0.0"
usb-ids = { version = "0.2.4", optional = true }
heck = "0.4.0"

[build-dependencies]
version_check = "0.9.*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
clap = { version = "4.0.22", features = ["derive", "suggestions"] }
clap_complete = "4.0.6"
clap_mangen = "0.2.5"

[target.x86_64-unknown-linux-gnu.dependencies]
udev = { version = "^0.7.0", optional = true }
rusb = { version = "0.9.1" }
usb-ids = "0.2.4"

[features]
libusb = ["dep:rusb", "dep:usb-ids"]
udev = ["dep:udev"]
default = ["libusb"]

[[bin]]
name = "cyme"
path = "src/main.rs"
