[package]
name = "cyme"
authors = ["John Whittington <john@jbrengineering.co.uk>"]
description = "Modern port of lsusb to macOS using system_profiler output"
repository = "https://github.com/tuna-f1sh/cyme"
readme = "README.md"
license = "GPL-3.0-or-later"
version = "0.1.2"
edition = "2021"
keywords = ["usb", "lsusb", "system_profiler", "macos"]
categories = ["command-line-utilities"]
exclude = ["./img/*"]

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }
colored = "2.0.0"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
simple_logger = "4.0.0"
