on: [push, pull_request]

name: build

env:
  PROJECT_NAME: cyme

jobs:
  build_and_test:
    name: Build and test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: test
        run: cargo test
      - name: build
        run: cargo build --release --all-features
      - name: archive executable
        uses: actions/upload-artifact@master
        with:
          name: ${{ env.PROJECT_NAME }}
          # name: ${{ env.PROJECT_NAME }}-${{ matrix.job.target }}
          path: target/release/${{ env.PROJECT_NAME }}
          # TODO ref https://github.com/Peltoche/lsd/blob/master/.github/workflows/CICD.yml for multi platform
          # path: target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}${{ steps.vars.outputs.EXE_suffix }}
