on: [push]

name: build

jobs:
  build_and_test:
    name: Build cyma
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: test
        run: cargo test
      - name: build
        run: cargo build --release --all-features
