name: Manually deploy release to homebrew

on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The git tag name to bump the formula to'
        required: true

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v2
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: cyme
          formula-path: Formula/cyme.rb
          homebrew-tap: tuna-f1sh/homebrew-taps
          tag-name: ${{ github.event.inputs.tag-name }}
          download-url: https://github.com/tuna-f1sh/cyme/releases/download/${{ github.event.inputs.tag-name }}/cyme-${{ github.event.inputs.tag-name }}-x86_64-apple-darwin.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

